[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#7c3aed"
backgroundColor = "#f1f5f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#1e293b"
font = "sans serif"
